services:
  db:
    image: postgres:16-alpine
    container_name: sftx-postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sanlam_loyalty_wallet"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: stfx-api-service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: .
          target: /code
          action: sync
          ignore:
            - .git/
            - venv/
            - __pycache__/
            - db.sqlite3
        - path: ./requirements.txt
          action: rebuild

volumes:
  postgres_data: